import _ from 'lodash';

export const getRandomExpression = () => {
    const operators = ['+', '-', '*'];
    //max random number will be 29, so that expressions won't be too difficult
    const firstOperand = Math.floor(Math.random() * 30);
    const secondOperand = Math.floor(Math.random() * 30);
    const operator = _.sample(operators);
    return `${firstOperand} ${operator} ${secondOperand}`;
}

export const expressionResult = (string) => {
    //code inside eval() is generated by us, so it's not potentially dangerous
    return String(eval(string));
}

